# Generated by Django 6.1 on 2026-08-18 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_scientifique', models.CharField(blank=True, max_length=150)),
                ('famille', models.CharField(blank=True, max_length=100)),
                ('ordre', models.CharField(blank=True, max_length=100)),
                ('nom_femelle', models.CharField(blank=True, max_length=100)),
                ('nom_male', models.CharField(blank=True, max_length=100)),
                ('nom_petit', models.CharField(blank=True, max_length=100)),
                ('nom_groupe', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='animaux/')),
                ('cri', models.FileField(blank=True, null=True, upload_to='cris/')),
                ('habitat', models.CharField(blank=True, max_length=200)),
                ('continent', models.CharField(blank=True, max_length=100)),
                ('regime_alimentaire', models.CharField(blank=True, max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=100)),
                ('anecdote', models.TextField(blank=True)),
                ('niveau_difficulte', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ModeJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeconDuJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('contenu_supplementaire', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('date_partie', models.DateTimeField(auto_now_add=True)),
                ('joueur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.modejeu')),
            ],
        ),
    ]
