# Generated by Django 6.1 on 2026-08-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='famille_nom_commun',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
