# Generated by Django 6.1 on 2026-08-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_animal_famille_nom_commun'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='nom_cri',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
